### ISSUE TITLE
Use rust-tools.nvim

### ISSUE THREAD

**Issue by sharksforarms** [sharksforarms/vim-rust#10]
Add @simrat39 [rust-tools.nvim](https://github.com/simrat39/rust-tools.nvim) to config

**Comment by sharksforarms** [comment]
Added https://github.com/sharksforarms/vim-rust/commit/cb1e7f0f5c9d5d0fd34ad25c239ae55be3f82408

**Comment by nicos68** [comment]
It eats ~ 400MB of memory on my setup. Is it the same for you ?
