### ISSUE TITLE
Is there a convenient way to change cargo's features or targets?

### ISSUE THREAD

**Issue by jneem** [sharksforarms/vim-rust#11]
Sometimes I'm working on a project with feature and/or target-specific code, and I'd like to change my rust-analyzer configuration to get diagnostics for the feature and/or target that I'm currently working on. (i.e I want `nvim` to give me the same errors I'd get if I were running `cargo check --features=foo,bar --target=wasm32-unknown-unknown`).

Do you know how to do this? I found [this page](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/generated_config.adoc) suggesting that there's a `rust-analyzer.cargo.features` setting somewhere, but I couldn't figure out where to set it, let alone how to conveniently modify it on the fly...

**Comment by sharksforarms** [comment]
I don't have much experience doing this on the fly, but here's something to get you started in configuring rust-analyzer!


```lua
nvim_lsp.rust_analyzer.setup({
    --- ...
    settings = {
      ["rust-analyzer"] = {
        cargo = {
          features = { "foo", "bar" },
        }
      }
    }
})
```

**Comment by jneem** [comment]
That's super helpful, thanks! I'll play around with this to see if I can get something that can be conveniently toggled dynamically.

**Comment by sharksforarms** [comment]
@jneem Let me know if you've figured out a nice way to do this dynamically! So far I've just been editing my Cargo.toml.... There's probably a easier way with lua/global variable? Not sure if these can change on the fly?

**Comment by jneem** [comment]
I'm a bit embarrassed to say it, but my current workflow is just to edit my vim config every time I want to change features. I change them infrequently enough that I haven't bothered setting up a slicker workflow...
