### ISSUE TITLE
inlay hints fail

### ISSUE THREAD

**Issue by wuminzhe** [sharksforarms/vim-rust#14]
<img width="818" alt="Screen Shot 2021-06-01 at 5 58 39 PM" src="https://user-images.githubusercontent.com/1608576/120305252-2059b400-c303-11eb-89c2-566423cbb40a.png">

**Comment by sharksforarms** [comment]
Hi @wuminzhe can you provide more information such as a minimal config file to reproduce? Which config are you referring to in the repo? Unfortunately I can't do much with a screenshot 😅

**Comment by wuminzhe** [comment]
Seems your blog is different from this repo?

**Comment by sharksforarms** [comment]
> Seems your blog is different from this repo?

Yes the repo is more upto date. Updating the blog is on my to-do list.
