### ISSUE TITLE
compe#confirm seems to conflict with some vim plugins

### ISSUE THREAD

**Issue by wuminzhe** [sharksforarms/vim-rust#15]
I have not found the problems

**Comment by sharksforarms** [comment]
When creating an issue, it helps to include as much detail as possible. I don't know what your issue is so I can't help you much.

**Comment by wuminzhe** [comment]
Okay. For now, I just record it here. 
I will attach more detailed info. 
I really like neovim, and want to find the best config for rust development.

**Comment by sharksforarms** [comment]
Any updates? @wuminzhe

**Comment by sharksforarms** [comment]
Closing for now.
