### ISSUE TITLE
nvim-lsp: RA doesn't support `goto declaration`

### ISSUE THREAD

**Issue by frondeus** [sharksforarms/vim-rust#2]
Just one thing worth noting, so `gd` won't work with Rust. You have to use `goto definition` instead.

**Comment by sharksforarms** [comment]
Are you referring to this line? https://github.com/sharksforarms/vim-rust/blob/master/neovim-init-lsp.vim#L64

You're right. I'll change this.

(love the test-case crate btw :+1: )

**Comment by sharksforarms** [comment]
Changed on master
