### ISSUE TITLE
rust-tools breaking changes

### ISSUE THREAD

**Issue by zbraniecki** [sharksforarms/vim-rust#24]
The configs should be updated to reflect https://github.com/simrat39/rust-tools.nvim/issues/232

**Comment by sharksforarms** [comment]
PRs welcome! I haven't updated my personal environment yet to these changes.

**Comment by sharksforarms** [comment]
Updated in https://github.com/sharksforarms/neovim-rust/commit/0410dcf393bfd094883326eac97c486f656ec556
