### ISSUE TITLE
nvim-lsp: inlay hints not working?

### ISSUE THREAD

**Issue by lnicola** [sharksforarms/vim-rust#4]
![image](https://user-images.githubusercontent.com/308347/106499548-66277c80-64c9-11eb-8704-fa969864ebc9.png)

I'm using your snippet:

```vimscript
autocmd CursorMoved,InsertLeave,BufEnter,BufWinEnter,TabEnter,BufWritePost *
\ lua require'lsp_extensions'.inlay_hints{ prefix = '', highlight = "Comment" }
```

Tested with `nvim 0.5.0+dev+1062+gcc1851c9f-1`.

**Comment by lnicola** [comment]
Found https://github.com/nvim-lua/lsp_extensions.nvim/issues/20, but the suggestion there doesn't seem to do anything for me.

**Comment by lnicola** [comment]
Actually they do show up, but only after editing the code? https://asciinema.org/a/wBwj7uKmjeSmN4fL8KgBuYddI

Right now I have:

```vimscript
+ autocmd BufEnter,BufWinEnter,TabEnter *.rs :lua require'lsp_extensions'.inlay_hints{ prefix = '', highlight = "Comment", enabled = {"TypeHint", "ChainingHint", "ParameterHint"}}
```

**Comment by sharksforarms** [comment]
It will only start showing once the LSP kicks in (rust-analyzer) which for me seems to be after first write (`:w`)

**Comment by lnicola** [comment]
Hmm, for me LSP features are working even before a `:w`, and I see the server starting up right from the beginning.

**Comment by sharksforarms** [comment]
I can take a look at this later tonight, could you provide your config?

**Comment by lnicola** [comment]
Sorry, it's a bit messy: https://gist.github.com/lnicola/1276f4c205361960ffd23b1a4c2cea62

Anyway, don't worry, this doesn't seem terribly important.

**Comment by sharksforarms** [comment]
I believe it's your autocmds combination. For example, triggering any of those autocmds makes them show properly.

I think what's happening is that the LSP isn't started yet when the file opens, so the request for hints fails. Could be possible to call inlay hints when the LSP is started?

You could also try adding a more frequent autocmd like `CursorHold`


Here is my list: `autocmd BufEnter,BufWinEnter,BufWritePost,InsertLeave,TabEnter`

**Comment by sharksforarms** [comment]
Let me know if you need anything else!

**Comment by ruffson** [comment]
I have the same problem, inlay hints stopped working for whatever reason. When I Iook at the lsp.log in `~/.cache/nvim` right after opening a workspace with a few buffers it says: 
```
[ WARN ] 2021-03-12T14:17:26+0100 ] ...ount_nvim.aNPuIQD/usr/share/nvim/runtime/lua/vim/lsp.lua:84 ]    "method rust-analyzer/inlayHints is not supported by any of the servers registered for the current buffer"
```
I am using the `appimage` neovim bin. If I use your exact config file, I do have inlay hints but when I use [mine](https://github.com/ruffson/dotfiles/blob/nvim_prerelease/init.vim) which contains your settings almost excately it doesn't anymore. Which is driving me mad. I have no idea what is happening here. The only thing that is different from yours is that my plugs are in the default neovim folder and not in `~/.vim/`.

The `rust_analyzer` is available in my path. Do you have any idea what this could be or how I could debug it?
When I do `:LspInfo` everything looks correct.

**Comment by Antonio-Bennett** [comment]
> I have the same problem, inlay hints stopped working for whatever reason. When I Iook at the lsp.log in `~/.cache/nvim` right after opening a workspace with a few buffers it says:
> 
> ```
> [ WARN ] 2021-03-12T14:17:26+0100 ] ...ount_nvim.aNPuIQD/usr/share/nvim/runtime/lua/vim/lsp.lua:84 ]    "method rust-analyzer/inlayHints is not supported by any of the servers registered for the current buffer"
> ```
> 
> I am using the `appimage` neovim bin. If I use your exact config file, I do have inlay hints but when I use [mine](https://github.com/ruffson/dotfiles/blob/nvim_prerelease/init.vim) which contains your settings almost excately it doesn't anymore. Which is driving me mad. I have no idea what is happening here. The only thing that is different from yours is that my plugs are in the default neovim folder and not in `~/.vim/`.
> 
> The `rust_analyzer` is available in my path. Do you have any idea what this could be or how I could debug it?
> When I do `:LspInfo` everything looks correct.

Did you figure it out? Getting the same issue as well I have the rust analyzer binary installed configured correctly with native lsp and same here :LspInfo shows rust-analyzer is registered

**Comment by ruffson** [comment]
@Antonio-Bennett Man I have no idea. It worked for me again. But I don't remember why and what changed. No single action I took, brought it back but rather changing everything, re-installing everything out of desperation, etc.
 [This](https://github.com/ruffson/dotfiles/blob/nvim_prerelease/init.vim) is my current init.vim but as with your experience there is no clear reason why it should not have worked previously.

**Comment by Antonio-Bennett** [comment]
Lool same! Just started working all of a sudden!

**Comment by marcelmanz** [comment]
Any news about how to make this work? :)

**Comment by Antonio-Bennett** [comment]
Hey @marcelarie I use the lsp_extensions plugin found here https://github.com/nvim-lua/lsp_extensions.nvim then I add this to my init.lua or init.vim whichever one you have 
```vim 
vim.cmd [[ autocmd CursorMoved,InsertLeave,BufEnter,BufWinEnter,TabEnter,BufWritePost * :lua require'lsp_extensions'.inlay_hints{ prefix = '=>', highlight = "Comment", enabled = {"TypeHint", "ChainingHint", "ParameterHint"} } ]]
```

**Comment by sharksforarms** [comment]
@marcelarie I recommend basing off of: https://github.com/sharksforarms/vim-rust/blob/master/neovim-init-lsp-compe-rust-tools.vim

This uses https://github.com/simrat39/rust-tools.nvim which supports inlay hints and more

**Comment by marcelmanz** [comment]
Ok I tried rust-tools and its really good, I am going to stick with that👌 thanks to both!!

**Comment by Antonio-Bennett** [comment]
Ouuu Rust tools looks real nice think im gonna switch over as well 😂
