### ISSUE TITLE
Return does not fill in arguments

### ISSUE THREAD

**Issue by ruffson** [sharksforarms/vim-rust#7]
Hi there,
I integrated your config to [my init.vim](https://github.com/ruffson/dotfiles/blob/nvim_prerelease/init.vim). Most things work but when I `tab` through the suggestions and press enter, it just completes the function name but does not add the function arguments or the brackets. See here:

![completion](https://user-images.githubusercontent.com/1185812/110238609-d4d17d00-7f42-11eb-8152-d9b8aba9880d.gif)

Any idea why this happens? I also tried to reduce the config, remove the lspsaga stuff, but that did not help either.

**Comment by sharksforarms** [comment]
Does this happen with the configuration in the repo? Are you able to reproduce it with the docker setup? If you provide a minimal vimrc I can take a look.

**Comment by ruffson** [comment]
> Does this happen with the configuration in the repo? Are you able to reproduce it with the docker setup? If you provide a minimal vimrc I can take a look.

Yes the problem occurs also with your [config](https://github.com/sharksforarms/vim-rust/blob/master/neovim-init-lsp.vim).

I tried with the latest dev release:  `NVIM v0.5.0-dev+1126-g0496b572a`.

**Comment by ruffson** [comment]
~~Also the the inlay hints kill other lsp clients. E.g. when I am opening a Julia file and start moving around it straigt up crashes.~~

~~These lines should be rust-specific and not be applied in general:~~
```
autocmd CursorMoved,InsertLeave,BufEnter,BufWinEnter,TabEnter,BufWritePost *
\ lua require'lsp_extensions'.inlay_hints{ prefix = '', highlight = "Comment", enabled = {"TypeHint", "ChainingHint", "ParameterHint"} }
```
~~otherwise a `"Unknown method rust-analyzer/inlayHints."` error will be raised and kill other lsp clients.~~

Fixed.

**Comment by ruffson** [comment]
I just tried your docker image and have the same problem.

With `neovim-init-lsp.vim`:
![lsp1](https://user-images.githubusercontent.com/1185812/110988321-b0293b00-8370-11eb-974f-846aa8a5fcca.gif)

With `neovim-init-lsp-compe.vim`:
![compe](https://user-images.githubusercontent.com/1185812/110988373-bd462a00-8370-11eb-96ce-ee67b3ce516e.gif)

**Comment by sharksforarms** [comment]
I can take a look this weekend

**Comment by sharksforarms** [comment]
See latest master

**Comment by ruffson** [comment]
Awesome, thank you that solves almost everything!

Thank you so much!

One last thing, do you know how to get the proper function singature with compe when tabbing?
I get the correct docs when I `K` but when I use `<tab>` it never shows the correct function signature and I only have this problem with compe:
(In this case it only says `-> Self`, the top part is cut off)
![Screenshot from 2021-03-14 20-41-09](https://user-images.githubusercontent.com/1185812/111081946-fe237780-8505-11eb-8e3c-8498162ba390.png)
Whereas this is what I would expect (and what I get with `K`):

![Screenshot from 2021-03-14 20-46-19](https://user-images.githubusercontent.com/1185812/111082022-72f6b180-8506-11eb-897d-8ce3de1e5fff.png)

**Comment by ruffson** [comment]
FYI this last issue was just recently [fixed](https://github.com/rust-analyzer/rust-analyzer/pull/7900) in the `rust-anaylzer` repo.

//fixed link.

**Comment by sharksforarms** [comment]
@ruffson thanks for the update!
