### ISSUE TITLE
:PlugInstall doesn't work with nvim

### ISSUE THREAD

**Issue by keblek** [sharksforarms/vim-rust#9]
`Cannot source a directory: "/root/.config/nvim/init.vim"` when I run nvim and I can't run PlugInstall

Any tips?

**Comment by sharksforarms** [comment]
Do you mean the docker container? I added a ./run.sh script in the root of the repo, check it out and let me know!

**Comment by keblek** [comment]
I actually decided to give a Lua based config a try thanks though!

**Comment by sharksforarms** [comment]
> 
> 
> I actually decided to give a Lua based config a try thanks though!

That's a better way of doing it ;) I'd be interested in having a lua based config in the repo if you're interested!

**Comment by keblek** [comment]
Sure! I am currently following this and it works pretty well https://alpha2phi.medium.com/neovim-init-lua-e80f4f136030 

What do you think about it?

**Comment by sharksforarms** [comment]
@keblek looks thorough! Would love a PR for a rust version :)
